-- Run this in Supabase SQL Editor when APP_MODE=cloud.
-- The FastAPI service uses this relational schema through SQLAlchemy.

create table if not exists users (
  id bigint generated by default as identity primary key,
  auth_uid varchar(128) unique not null,
  password_hash varchar(255),
  name varchar(120) not null,
  email varchar(255) unique not null,
  role varchar(20) not null check (role in ('student','teacher')),
  created_at timestamptz default now()
);

create table if not exists courses (
  id bigint generated by default as identity primary key,
  course_name varchar(150) not null,
  teacher_id bigint references users(id) not null,
  created_at timestamptz default now()
);

create table if not exists assignments (
  id bigint generated by default as identity primary key,
  course_id bigint references courses(id) not null,
  title varchar(200) not null,
  description text not null,
  deadline timestamptz not null,
  max_marks integer not null,
  allowed_file_types varchar(255) default 'pdf,docx',
  max_file_size_mb integer default 10,
  created_by bigint references users(id) not null,
  created_at timestamptz default now()
);

create table if not exists submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint references assignments(id) not null,
  student_id bigint references users(id) not null,
  file_name varchar(255) not null,
  storage_path varchar(500) unique not null,
  submitted_at timestamptz default now(),
  submission_status varchar(30) not null,
  marks integer,
  feedback text,
  graded_at timestamptz,
  version integer default 1
);

create index if not exists ix_assignments_course on assignments(course_id);
create index if not exists ix_assignments_deadline on assignments(deadline);
create index if not exists ix_submissions_assignment_student on submissions(assignment_id, student_id);
create index if not exists ix_submissions_status on submissions(submission_status);
